version: '3'
services:
  app:
    build: .
    environment:
      APP_MYSQL_HOST: mysql
      APP_MYSQL_PORT: 3306
      APP_MYSQL_USER: root
      APP_MYSQL_PASSWORD:
      APP_MYSQL_DATABASE: demo
    volumes:
      - .:/app
    depends_on:
      mysql:
        condition: service_healthy
    links:
      - mysql
    ports:
      - '8080:8080'
    tty: true

  mysql:
    image: mysql:8.0
    platform: linux/amd64
    volumes:
      - ./containers/mysql:/etc/mysql/conf.d/
      - mysql:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h mysql -P 3306 -u root
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '4306:3306'
volumes:
  mysql:
