name: CI

on:
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: 'CI'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        go-version: ['1.20']

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3

      - name: Set up Go ✨
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
          cache-dependency-path: go.sum

      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.51.2
          working-directory: .
          args: "--config ./.golangci.yml --verbose ./..."
          github-token: ${{ secrets.github_token }}
          skip-cache: true

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
